### ISSUE TITLE
CPU default for autoscale

### ISSUE THREAD

**Issue by sahar2339** [dana-team/container-app-operator#3]
Right now if `scaleMetric` is nill the controller doesn't apply any AutoScaler to the knative serivce.
We need to change it to a default value of `CPU` based scaling.

/assign @omer5yerushalmi

**Comment by omer5yerushalmi** [comment]
We will fix it with MutatingWebhookConfiguration.

**Comment by mzeevi** [comment]
Do we still intend to do it? I think we took care of it on the deployer level?

**Comment by omer5yerushalmi** [comment]
Yes, @omerbd21 fixed that.
