### ISSUE TITLE
Bug: CleanUp method can delete non-existing flow & output

### ISSUE THREAD

**Issue by liadlauber** [dana-team/container-app-operator#46]
The CleanUp method in the FlowManager and OutputManager struct does not handle the scenario where the flow resource associated with the Capp object does not exist. As a result, when CleanUp is called and the flow resource does not exist, the method will attempt to delete a non-existing object, which can lead to unexpected errors.

To address this issue, the CleanUp method should first check if the flow resource exists before attempting to delete it. If the flow does not exist, it should return early without attempting to delete the resource.

https://github.com/dana-team/container-app-operator/blob/11d7a3335bcdd52812655eee52fbe2295863ba6c/internals/resource-managers/flow.go#L63-L73

https://github.com/dana-team/container-app-operator/blob/11d7a3335bcdd52812655eee52fbe2295863ba6c/internals/resource-managers/output.go#L130-L140

**Comment by mzeevi** [comment]
Closing since this is unnecessary
