### ISSUE TITLE
Enforce tlsSecret Requirement When tlsEnabled is Set in routeSpec

### ISSUE THREAD

**Issue by liadlauber** [dana-team/container-app-operator#80]
In the Capp CRD, when `tlsEnabled: true` is set in `routeSpec`, it should be mandatory to provide the `tlsSecret` as well. Currently, it is possible to create a Capp with `tlsEnabled: true` but without specifying `tlsSecret`, which leads to unexpected behavior.

Based on domainMapping test 3 in https://docs.google.com/document/d/1v1L-FFZwTB3HC4bnCFvTRAd-axK4Mi-bkhgXpWLbPJ0

**Comment by mzeevi** [comment]
https://github.com/dana-team/rcs-ocm-deployer/pull/128
