### ISSUE TITLE
Ensure TLS Secret Existence Check Before Approving Capp CRD

### ISSUE THREAD

**Issue by liadlauber** [dana-team/container-app-operator#81]
The current implementation of the Capp CRD allows the specification of a TLS secret in the tlsSecret field within the routeSpec. However, there is no check in place to ensure that the specified TLS secret actually exists on the Kubernetes cluster before approving the CRD.

Based on domainMapping test 4 in https://docs.google.com/document/d/1v1L-FFZwTB3HC4bnCFvTRAd-axK4Mi-bkhgXpWLbPJ0

**Comment by mzeevi** [comment]
Closed by https://github.com/dana-team/rcs-ocm-deployer/pull/128
