### ISSUE TITLE
Rename to cappStateAnnotation and change group to capp.dana.io

### ISSUE THREAD

**Issue by fran2810** [dana-team/container-app-operator#86]
https://github.com/dana-team/container-app-operator/blob/dd6668423a7e4704a2d41c76bdf8c34647c3986d/internals/utils/common.go#L12

https://github.com/dana-team/container-app-operator/blob/dd6668423a7e4704a2d41c76bdf8c34647c3986d/internals/resource-managers/knative_service.go#L24

**Comment by mzeevi** [comment]
Closed by #87
