### ISSUE TITLE
Cluster segment assumes Class C segments which may not be true

### ISSUE THREAD

**Issue by mzeevi** [dana-team/container-app-operator#92]
There is no guarantee that the cluster segments would be Class C, they can pretty much be anything. We need to either figure out how to find the real segment, or just remove this functionality all together.

https://github.com/dana-team/container-app-operator/blob/1c1cfc145beb79b1b36ef670afe441221304f83e/internals/utils/status/application_links.go#L55-L68

/kind bug

**Comment by sahar2339** [comment]
fixed with #104
